#!/usr/bin/env python3
"""Validate noindex directives and local links in the assembled static site."""

from __future__ import annotations

import argparse
import sys
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit


REQUIRED_FILES = (
    Path("index.html"),
    Path("robots.txt"),
    Path("rust-hft/index.html"),
    Path("rust-hft/robots.txt"),
    Path("ai/index.html"),
    Path("ai/robots.txt"),
)
GENERATED_REDIRECT_MARKER = "<!-- generated by scripts/create_legacy_redirects.py -->"


class PageParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.has_noindex = False
        self.urls: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        values = {key.lower(): value or "" for key, value in attrs}
        if tag.lower() == "meta" and values.get("name", "").lower() == "robots":
            directives = {
                item.strip().lower()
                for item in values.get("content", "").split(",")
            }
            self.has_noindex = self.has_noindex or "noindex" in directives

        for attribute in ("href", "src"):
            if attribute in values:
                self.urls.append(values[attribute])


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="检查统一站点的 noindex、必要入口和本地页面/静态资源链接。"
    )
    parser.add_argument(
        "site_root",
        metavar="SITE_ROOT",
        help="显式指定已经组装完成的 site 目录",
    )
    parser.add_argument(
        "--url-prefix",
        default="/hft-book-rs/",
        help="部署时映射到 SITE_ROOT 的 URL 前缀（默认：/hft-book-rs/）",
    )
    return parser.parse_args(argv)


def is_within(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


def local_target(
    raw_url: str,
    page: Path,
    site_root: Path,
    url_prefix: str,
) -> tuple[Path | None, str | None]:
    """Resolve a local URL, returning an explanatory error for invalid roots."""
    if not raw_url or raw_url.startswith(("#", "//")):
        return None, None

    parsed = urlsplit(raw_url)
    if parsed.scheme or parsed.netloc:
        return None, None

    url_path = unquote(parsed.path)
    if not url_path:
        return None, None

    prefix_without_slash = url_prefix.rstrip("/")
    if url_path == prefix_without_slash:
        target = site_root
    elif url_path.startswith(url_prefix):
        target = site_root / url_path.removeprefix(url_prefix)
    elif url_path.startswith("/"):
        return None, f"站点绝对路径没有使用部署前缀 {url_prefix}"
    else:
        target = page.parent / url_path

    resolved = target.resolve(strict=False)
    if not is_within(resolved, site_root):
        return None, "链接解析后越出 site 目录"
    if resolved.is_dir():
        resolved = resolved / "index.html"
    return resolved, None


def main(argv: list[str] | None = None) -> int:
    arguments = parse_args(sys.argv[1:] if argv is None else argv)
    site_root = Path(arguments.site_root).expanduser().resolve()
    url_prefix = arguments.url_prefix
    if not url_prefix.startswith("/") or not url_prefix.endswith("/"):
        print("ERROR: --url-prefix 必须以 / 开头和结尾", file=sys.stderr)
        return 1
    if not site_root.is_dir():
        print(f"ERROR: site 目录不存在: {site_root}", file=sys.stderr)
        return 1

    errors: list[str] = []
    for required in REQUIRED_FILES:
        if not (site_root / required).is_file():
            errors.append(f"缺少统一站点文件: {required.as_posix()}")

    pages = sorted(site_root.rglob("*.html"))
    if not pages:
        errors.append("site 中没有 HTML 页面")

    redirect_count = 0
    for page in pages:
        relative_page = page.relative_to(site_root).as_posix()
        text = page.read_text(encoding="utf-8")
        parser = PageParser()
        parser.feed(text)

        if not parser.has_noindex:
            errors.append(f"页面缺少 robots noindex: {relative_page}")
        if text.startswith(GENERATED_REDIRECT_MARKER):
            redirect_count += 1

        for raw_url in parser.urls:
            target, reason = local_target(
                raw_url,
                page,
                site_root,
                url_prefix,
            )
            if reason:
                errors.append(f"无效本地链接: {relative_page} -> {raw_url}（{reason}）")
            elif target is not None and not target.exists():
                errors.append(f"本地链接目标不存在: {relative_page} -> {raw_url}")

    unique_errors = list(dict.fromkeys(errors))
    for error in unique_errors:
        print(f"ERROR: {error}", file=sys.stderr)

    if unique_errors:
        print(
            f"Site check failed with {len(unique_errors)} unique error(s).",
            file=sys.stderr,
        )
        return 1

    print(
        f"Site check passed: {len(pages)} HTML page(s), all noindex, "
        f"all local links resolved, {redirect_count} legacy redirect(s)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
