#!/usr/bin/env python3
"""Create noindex legacy redirects for a built rust-hft mdBook."""

from __future__ import annotations

import argparse
import html
import json
import os
import sys
from pathlib import Path
from urllib.parse import quote


GENERATED_MARKER = "<!-- generated by scripts/create_legacy_redirects.py -->"
PROTECTED_PORTAL_PAGES = {
    Path("index.html"),
    Path("404.html"),
    Path("toc.html"),
}


def is_within(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


def redirect_document(target_url: str) -> str:
    escaped_url = html.escape(target_url, quote=True)
    javascript_url = json.dumps(target_url, ensure_ascii=False)
    return f"""{GENERATED_MARKER}
<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="noindex, nofollow, noarchive, nosnippet, noimageindex">
  <meta http-equiv="refresh" content="0; url={escaped_url}">
  <link rel="canonical" href="{escaped_url}">
  <title>页面已迁移</title>
  <script>
    const target = {javascript_url};
    window.location.replace(target + window.location.search + window.location.hash);
  </script>
</head>
<body>
  <p>页面已迁移到 <a href="{escaped_url}">{escaped_url}</a>。</p>
</body>
</html>
"""


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "把 SITE_ROOT/rust-hft/**/*.html 映射成 SITE_ROOT 下的 noindex 旧地址跳转页"
        )
    )
    parser.add_argument(
        "site_root",
        metavar="SITE_ROOT",
        help="显式指定已经构建完成、且包含 rust-hft/ 的 site 目录",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    arguments = parse_args(sys.argv[1:] if argv is None else argv)
    site_root = Path(arguments.site_root).expanduser().resolve()
    rust_hft_root = (site_root / "rust-hft").resolve()

    if not site_root.is_dir():
        print(f"ERROR: site 目录不存在: {site_root}", file=sys.stderr)
        return 1
    if not rust_hft_root.is_dir() or not is_within(rust_hft_root, site_root):
        print(f"ERROR: 缺少受 site 约束的 rust-hft 构建目录: {rust_hft_root}", file=sys.stderr)
        return 1

    plans: list[tuple[Path, str]] = []
    skipped: list[Path] = []
    for source in sorted((site_root / "rust-hft").rglob("*.html")):
        if source.is_symlink():
            print(f"ERROR: 不接受符号链接 HTML 源文件: {source}", file=sys.stderr)
            return 1
        source_resolved = source.resolve()
        if not is_within(source_resolved, rust_hft_root):
            print(f"ERROR: HTML 源文件越出 rust-hft: {source}", file=sys.stderr)
            return 1

        relative = source.relative_to(site_root / "rust-hft")
        if any(part in ("", ".", "..") for part in relative.parts):
            print(f"ERROR: 非法相对路径: {relative}", file=sys.stderr)
            return 1
        if relative in PROTECTED_PORTAL_PAGES:
            skipped.append(relative)
            continue

        destination = site_root / relative
        destination_resolved = destination.resolve(strict=False)
        if not is_within(destination_resolved, site_root):
            print(f"ERROR: 跳转页目标越出 site: {destination}", file=sys.stderr)
            return 1
        if is_within(destination_resolved, rust_hft_root):
            print(f"ERROR: 拒绝覆盖 rust-hft 构建产物: {destination}", file=sys.stderr)
            return 1

        target = site_root / "rust-hft" / relative
        target_relative = os.path.relpath(target, start=destination.parent)
        target_url = quote(Path(target_relative).as_posix(), safe="/.")

        if destination.exists():
            if not destination.is_file():
                print(f"ERROR: 跳转页位置不是普通文件: {destination}", file=sys.stderr)
                return 1
            existing = destination.read_text(encoding="utf-8")
            if GENERATED_MARKER not in existing:
                print(f"ERROR: 拒绝覆盖非本脚本生成的文件: {destination}", file=sys.stderr)
                return 1
        plans.append((destination, target_url))

    if not plans:
        print("ERROR: rust-hft 构建目录中没有可映射的 HTML", file=sys.stderr)
        return 1

    for destination, target_url in plans:
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(redirect_document(target_url), encoding="utf-8")

    print(
        f"Generated {len(plans)} legacy redirect page(s) under {site_root}; "
        f"protected {len(skipped)} portal page(s)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
